framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        routing:
            'App\Message\RawLogLineMessage': async

when@test:
    framework:
        messenger:
            transports:
                async: test://